#ifndef FT_IRC_SERVER_RESPONSE
#define FT_IRC_SERVER_RESPONSE

enum Response {
	RPL_NONE = 300,
	RPL_NAMREPLY = 353,
	RPL_TOPIC = 332,
	ERR_NOSUCHNICK = 401,
	ERR_NOSUCHCHANNEL = 403,
	ERR_NORECIPIENT = 411,
	ERR_NOTEXTTOSEND = 412,
	ERR_NONICKNAMEGIVEN = 431,
	ERR_ERRONEUSNICKNAME = 432,
	ERR_NICKNAMEINUSE = 433,
	ERR_NICKCOLLISION = 436,
	ERR_NOTREGISTERED = 451,
	ERR_NEEDMOREPARAMS = 461,
	ERR_ALREADYREGISTRED = 462,
};

#endif /* FT_IRC_SERVER_RESPONSE */
